import { useState, useEffect } from 'react'
import { supabase } from './supabaseClient'
import Auth from './Auth'
import Chat from './Chat'
import ConversationList from './ConversationList'
import Profile from './Profile'
import { colors } from './colors'
import './App.css'

function App() {
  const [session, setSession] = useState(null)
    const [loading, setLoading] = useState(true)
      const [activeConversationId, setActiveConversationId] = useState(null)
        const [showProfile, setShowProfile] = useState(false)

          useEffect(() => {
              supabase.auth.getSession().then(({ data: { session } }) => {
                    setSession(session)
                          setLoading(false)
                              })

                                  const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
                                        setSession(session)
                                            })

                                                return () => subscription.unsubscribe()
                                                  }, [])

                                                    const handleLogout = async () => {
                                                        await supabase.auth.signOut()
                                                          }

                                                            if (loading) {
                                                                return (
                                                                      <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: colors.background }}>
                                                                              <p style={{ color: colors.textLight }}>Chargement...</p>
                                                                                    </div>
                                                                                        )
                                                                                          }

                                                                                            if (!session) {
                                                                                                return <Auth />
                                                                                                  }

                                                                                                    if (showProfile) {
                                                                                                        return <Profile session={session} onBack={() => setShowProfile(false)} />
                                                                                                          }

                                                                                                            return (
                                                                                                                <div style={{ minHeight: '100vh', background: colors.background }}>
                                                                                                                      {!activeConversationId && (
                                                                                                                              <div
                                                                                                                                        style={{
                                                                                                                                                    background: colors.blueDark,
                                                                                                                                                                padding: '10px 16px',
                                                                                                                                                                            display: 'flex',
                                                                                                                                                                                        justifyContent: 'space-between',
                                                                                                                                                                                                    alignItems: 'center',
                                                                                                                                                                                                                color: colors.white,
                                                                                                                                                                                                                            fontSize: 13
                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                        <span>{session.user.email}</span>
                                                                                                                                                                                                                                                                  <div style={{ display: 'flex', gap: 10 }}>
                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                            onClick={() => setShowProfile(true)}
                                                                                                                                                                                                                                                                                                          style={{ background: 'none', border: 'none', color: colors.yellow, cursor: 'pointer', fontWeight: 600, fontSize: 13 }}
                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                    Mon profil
                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                          onClick={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                        style={{ background: 'none', border: 'none', color: colors.white, cursor: 'pointer', fontSize: 13 }}
                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                  Déconnexion
                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                            {activeConversationId ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Chat
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              session={session}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conversationId={activeConversationId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onBack={() => setActiveConversationId(null)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ConversationList
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  session={session}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onSelectConversation={(id) => setActiveConversationId(id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default App