import { useState } from 'react'
import { supabase } from './supabaseClient'
import { colors } from './colors'

export default function CreateGroup({ session, contacts, onGroupCreated, onCancel }) {
  const [groupName, setGroupName] = useState('')
    const [selectedIds, setSelectedIds] = useState([])
      const [loading, setLoading] = useState(false)

        const toggleContact = (userId) => {
            setSelectedIds((prev) =>
                  prev.includes(userId) ? prev.filter((id) => id !== userId) : [...prev, userId]
                      )
                        }

                          const handleCreateGroup = async () => {
                              if (!groupName.trim()) {
                                    alert('Donne un nom au groupe')
                                          return
                                              }
                                                  if (selectedIds.length < 2) {
                                                        alert('Sélectionne au moins 2 personnes')
                                                              return
                                                                  }

                                                                      setLoading(true)

                                                                          const { data: { user } } = await supabase.auth.getUser()

                                                                              const { data: newConv, error: convError } = await supabase
                                                                                    .from('conversations')
                                                                                          .insert({ type: 'group', name: groupName.trim(), created_by: user.id })
                                                                                                .select()
                                                                                                      .single()

                                                                                                          if (convError) {
                                                                                                                alert('Erreur création groupe : ' + convError.message)
                                                                                                                      setLoading(false)
                                                                                                                            return
                                                                                                                                }

                                                                                                                                    const participantsToInsert = [
                                                                                                                                          { conversation_id: newConv.id, user_id: user.id },
                                                                                                                                                ...selectedIds.map((id) => ({ conversation_id: newConv.id, user_id: id }))
                                                                                                                                                    ]

                                                                                                                                                        const { error: partError } = await supabase
                                                                                                                                                              .from('conversation_participants')
                                                                                                                                                                    .insert(participantsToInsert)

                                                                                                                                                                        if (partError) {
                                                                                                                                                                              alert('Erreur ajout participants : ' + partError.message)
                                                                                                                                                                                    setLoading(false)
                                                                                                                                                                                          return
                                                                                                                                                                                              }

                                                                                                                                                                                                  setLoading(false)
                                                                                                                                                                                                      onGroupCreated(newConv.id)
                                                                                                                                                                                                        }
                                                                                                                                                                                                       return (
                                                                                                                                                                                                                 <div style={{ minHeight: '100vh', background: colors.background }}>
                                                                                                                                                                                                                       <div style={{ background: colors.blue, padding: '14px 16px', display: 'flex', alignItems: 'center', gap: 10, color: colors.white }}>
                                                                                                                                                                                                                               <button onClick={onCancel} style={{ border: 'none', background: 'none', color: colors.white, fontSize: 20, cursor: 'pointer' }}>
                                                                                                                                                                                                                                         ←
                                                                                                                                                                                                                                                 </button>
                                                                                                                                                                                                                                                         <h2 style={{ margin: 0, fontSize: 18 }}>Nouveau groupe</h2>
                                                                                                                                                                                                                                                               </div>

                                                                                                                                                                                                                                                                     <div style={{ maxWidth: 500, margin: '0 auto', padding: 20 }}>
                                                                                                                                                                                                                                                                             <div style={{ marginBottom: 18 }}>
                                                                                                                                                                                                                                                                                       <input
                                                                                                                                                                                                                                                                                                   type="text"
                                                                                                                                                                                                                                                                                                               placeholder="Nom du groupe"
                                                                                                                                                                                                                                                                                                                           value={groupName}
                                                                                                                                                                                                                                                                                                                                       onChange={(e) => setGroupName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                   style={{ width: '100%', padding: 12, borderRadius: 10, border: `1px solid ${colors.border}`, boxSizing: 'border-box' }}
                                                                                                                                                                                                                                                                                                                                                             />
                                                                                                                                                                                                                                                                                                                                                                     </div>

                                                                                                                                                                                                                                                                                                                                                                             <p style={{ color: colors.textLight, fontSize: 13, textTransform: 'uppercase', letterSpacing: 0.5 }}>
                                                                                                                                                                                                                                                                                                                                                                                       Sélectionne les participants
                                                                                                                                                                                                                                                                                                                                                                                               </p>

                                                                                                                                                                                                                                                                                                                                                                                                       {contacts.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                 <p style={{ color: colors.textLight, textAlign: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                             Aucun contact disponible. Démarre d'abord une conversation avec quelqu'un.
                                                                                                                                                                                                                                                                                                                                                                                                                                       </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                               ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                         <ul style={{ listStyle: 'none', padding: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     {contacts.map((contact) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <li
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   key={contact.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   onClick={() => toggleContact(contact.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     padding: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         marginBottom: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           cursor: 'pointer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 gap: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   background: selectedIds.includes(contact.id) ? colors.yellowLight : colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     border: selectedIds.includes(contact.id) ? `1px solid ${colors.yellow}` : '1px solid transparent',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       boxShadow: '0 1px 3px rgba(0,0,0,0.06)'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <input type="checkbox" checked={selectedIds.includes(contact.id)} readOnly />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <span style={{ color: colors.text }}>{contact.display_name || contact.username}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   onClick={handleCreateGroup}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               padding: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           marginTop: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       background: colors.blue,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   color: colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       fontWeight: 600,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   fontSize: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               cursor: loading ? 'default' : 'pointer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           opacity: loading ? 0.7 : 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {loading ? 'Création...' : 'Créer le groupe'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                       