import { useState, useEffect } from 'react'
import { supabase } from './supabaseClient'
import { colors } from './colors'

export default function Profile({ session, onBack }) {
  const [displayName, setDisplayName] = useState('')
    const [avatarUrl, setAvatarUrl] = useState('')
      const [loading, setLoading] = useState(true)
        const [uploading, setUploading] = useState(false)

          useEffect(() => {
              fetchProfile()
                }, [])

                  const fetchProfile = async () => {
                      const { data, error } = await supabase
                            .from('profiles')
                                  .select('display_name, avatar_url')
                                        .eq('id', session.user.id)
                                              .single()

                                                  if (!error && data) {
                                                        setDisplayName(data.display_name || '')
                                                              setAvatarUrl(data.avatar_url || '')
                                                                  }
                                                                      setLoading(false)
                                                                        }

                                                                          const updateDisplayName = async () => {
                                                                              if (!displayName.trim()) {
                                                                                    alert('Le nom ne peut pas être vide')
                                                                                          return
                                                                                              }

                                                                                                  const { error } = await supabase
                                                                                                        .from('profiles')
                                                                                                              .update({ display_name: displayName.trim() })
                                                                                                                    .eq('id', session.user.id)

                                                                                                                        if (error) {
                                                                                                                              alert('Erreur : ' + error.message)
                                                                                                                                  } else {
                                                                                                                                        alert('Nom mis à jour !')
                                                                                                                                            }
                                                                                                                                              }

                                                                                                                                                const handleAvatarChange = async (e) => {
                                                                                                                                                    const file = e.target.files[0]
                                                                                                                                                        if (!file) return

                                                                                                                                                            setUploading(true)

                                                                                                                                                                const fileExt = file.name.split('.').pop()
                                                                                                                                                                    const filePath = `avatars/${session.user.id}-${Date.now()}.${fileExt}`

                                                                                                                                                                        const { error: uploadError } = await supabase.storage
                                                                                                                                                                              .from('chat-attachments')
                                                                                                                                                                                    .upload(filePath, file)

                                                                                                                                                                                        if (uploadError) {
                                                                                                                                                                                              alert('Erreur upload : ' + uploadError.message)
                                                                                                                                                                                                    setUploading(false)
                                                                                                                                                                                                          return
                                                                                                                                                                                                              }

                                                                                                                                                                                                                  const { data: urlData } = supabase.storage
                                                                                                                                                                                                                        .from('chat-attachments')
                                                                                                                                                                                                                              .getPublicUrl(filePath)

                                                                                                                                                                                                                                  const { error: updateError } = await supabase
                                                                                                                                                                                                                                        .from('profiles')
                                                                                                                                                                                                                                              .update({ avatar_url: urlData.publicUrl })
                                                                                                                                                                                                                                                    .eq('id', session.user.id)

                                                                                                                                                                                                                                                        if (updateError) {
                                                                                                                                                                                                                                                              alert('Erreur : ' + updateError.message)
                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                        setAvatarUrl(urlData.publicUrl)
                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                setUploading(false)
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                    if (loading) {
                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                              <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: colors.background }}>
                                                                                                                                                                                                                                                                                                      <p style={{ color: colors.textLight }}>Chargement...</p>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                             return (
                                                                                                                                                                                                                                                                                                                       <div style={{ minHeight: '100vh', background: colors.background }}>
                                                                                                                                                                                                                                                                                                                             <div style={{ background: colors.blue, padding: '14px 16px', display: 'flex', alignItems: 'center', gap: 10, color: colors.white }}>
                                                                                                                                                                                                                                                                                                                                     <button onClick={onBack} style={{ border: 'none', background: 'none', color: colors.white, fontSize: 20, cursor: 'pointer' }}>
                                                                                                                                                                                                                                                                                                                                               ←
                                                                                                                                                                                                                                                                                                                                                       </button>
                                                                                                                                                                                                                                                                                                                                                               <h2 style={{ margin: 0, fontSize: 18 }}>Mon profil</h2>
                                                                                                                                                                                                                                                                                                                                                                     </div>

                                                                                                                                                                                                                                                                                                                                                                           <div style={{ maxWidth: 500, margin: '0 auto', padding: 24 }}>
                                                                                                                                                                                                                                                                                                                                                                                   <div style={{ textAlign: 'center', marginBottom: 24 }}>
                                                                                                                                                                                                                                                                                                                                                                                             {avatarUrl ? (
                                                                                                                                                                                                                                                                                                                                                                                                         <img
                                                                                                                                                                                                                                                                                                                                                                                                                       src={avatarUrl}
                                                                                                                                                                                                                                                                                                                                                                                                                                     alt="Avatar"
                                                                                                                                                                                                                                                                                                                                                                                                                                                   style={{ width: 110, height: 110, borderRadius: '50%', objectFit: 'cover', border: `3px solid ${colors.yellow}` }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                               />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   width: 110,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   height: 110,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   borderRadius: '50%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   background: colors.blueLight,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   margin: '0 auto',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   fontSize: 44
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           👤
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div style={{ marginTop: 12 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     type="file"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   id="avatarInput"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 accept="image/*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               onChange={handleAvatarChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             style={{ display: 'none' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   onClick={() => document.getElementById('avatarInput').click()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 disabled={uploading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               background: colors.yellowLight,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               color: colors.blueDark,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               border: `1px solid ${colors.yellow}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               borderRadius: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               padding: '8px 16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               cursor: uploading ? 'default' : 'pointer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               fontWeight: 600,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               fontSize: 13
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {uploading ? 'Envoi...' : 'Changer la photo'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div style={{ marginBottom: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <label style={{ fontSize: 13, color: colors.textLight }}>Nom d'affichage :</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div style={{ display: 'flex', gap: 8, marginTop: 6 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         value={displayName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       onChange={(e) => setDisplayName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     style={{ flex: 1, padding: 10, borderRadius: 8, border: `1px solid ${colors.border}` }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           onClick={updateDisplayName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         style={{ background: colors.blue, color: colors.white, border: 'none', borderRadius: 8, padding: '0 16px', cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Enregistrer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <p style={{ color: colors.textLight, fontSize: 13, textAlign: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Email : {session.user.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                             